# Sekolah FE

Daftar Pasien

## Get Patient List [/patient-list]
### Get All Patient List [GET]
+ Response 200 (application/json)

        [
            {
                "id":"5e91c564759d94d0e03bf499",
                "nama":"Maxwell Stewart",
                "umur":69,
                "status":"Positif",
                "kota":"Bengkulu"
            },
            {
                "id":"5e91c5648fff6b5d2d69eca9",
                "nama":"Marta Smith",
                "umur":88,
                "status":"Negatif",
                "kota":"Kupang"
            },
            {
                "id":"5e91c5646715f08ca3fec151",
                "nama":"Reyes Ware",
                "umur":53,
                "status":"Belum Diketahui",
                "kota":"Serang"
            },
            {
                "id":"5e91c56441679bf2b0e5cbf1",
                "nama":"Alston Bell",
                "umur":38,
                "status":"Positif",
                "kota":"Lampung"
            },
            {
                "id":"5e91c56498cb4f18fd808936",
                "nama":"Foreman Knight",
                "umur":100,
                "status":"Negatif",
                "kota":"Jakarta Selatan"
            },
            {
                "id":"5e91c5641ef3d48314d09afb",
                "nama":"Randall Kirk",
                "umur":39,
                "status":"Positif",
                "kota":"Tangerang Selatan"
            },
            {
                "id":"5e91c5641fc4e3b08b787374",
                "nama":"Harriet Whitley",
                "umur":81,
                "status":"Belum Diketahui",
                "kota":"Sabang"
            },
            {
                "id":"5e91c564eac2ba3afab2f769",
                "nama":"Loretta Boyd",
                "umur":59,
                "status":"Negatif",
                "kota":"Kotamobagu"
            },
            {
                "id":"5e91c564f708aae7b5eb6f99",
                "nama":"Chandler Delgado",
                "umur":70,
                "status":"Negatif",
                "kota":"Madiun"
            },
            {
                "id":"5e91c56425d8ef549fe837d0",
                "nama":"Leigh Rodriquez",
                "umur":23,
                "status":"Belum Diketahui",
                "kota":"Cilegon"
            },
            {
                "id":"5e91c56451a17f472135bc75",
                "nama":"James Wilkins",
                "umur":7,
                "status":"Negatif",
                "kota":"Tegal"
            },
            {
                "id":"5e91c5641c1cc57d2a736a13",
                "nama":"Ofelia Velez",
                "umur":53,
                "status":"Belum Diketahui",
                "kota":"Mataram"
            },
            {
                "id":"5e91c564c97d4e79d72a897b",
                "nama":"Walls Fleming",
                "umur":67,
                "status":"Positif",
                "kota":"Mojokerto"
            },
            {
                "id":"5e91c5644ba5f7882701fabf",
                "nama":"Jacquelyn Watkins",
                "umur":41,
                "status":"Belum Diketahui",
                "kota":"Padang Sidempuan"
            },
            {
                "id":"5e91c56408135d194c83f81d",
                "nama":"Browning Campos",
                "umur":13,
                "status":"Negatif",
                "kota":"Payakumbuh"
            },
            {
                "id":"5e91c564490c64d09cfe72dd",
                "nama":"Joanna Garrison",
                "umur":1,
                "status":"Positif",
                "kota":"Banjarmasi"
            },
            {
                "id":"5e91c5647412ef3520872d6e",
                "nama":"King Morin",
                "umur":87,
                "status":"Negatif",
                "kota":"Tanjungpinang"
            },
            {
                "id":"5e91c564856883ac986674ec",
                "nama":"Stephanie Holman",
                "umur":81,
                "status":"Negatif",
                "kota":"Ternate"
            },
            {
                "id":"5e91c56410d0f8d7a25fe938",
                "nama":"Constance Atkins",
                "umur":43,
                "status":"Negatif",
                "kota":"Tangerang Selatan"
            },
            {
                "id":"5e91c564fea48b1a0977df35",
                "nama":"Palmer Weeks",
                "umur":42,
                "status":"Positif",
                "kota":"Gorontalo"
            },
            {
                "id":"5e91c5642f270586cb913c3e",
                "nama":"Bright Wiggins",
                "umur":76,
                "status":"Belum Diketahui",
                "kota":"Malang"
            },
            {
                "id":"5e91c564d87d825e587499ed",
                "nama":"Deana Bailey",
                "umur":65,
                "status":"Negatif",
                "kota":"Kotamobagu"
            },
            {
                "id":"5e91c56434fc163eb869661c",
                "nama":"Darla Donaldson",
                "umur":10,
                "status":"Positif",
                "kota":"Magelang"
            },
            {
                "id":"5e91c5641b2fc44abbaea049",
                "nama":"Myra Duke",
                "umur":73,
                "status":"Belum Diketahui",
                "kota":"Batam"
            },
            {
                "id":"5e91c56401e3fff3f8d82dd7",
                "nama":"Marsh Weber",
                "umur":12,
                "status":"Belum Diketahui",
                "kota":"Langsa"
            },
            {
                "id":"5e91c564d90cc300ce6c178a",
                "nama":"Imelda Rosario",
                "umur":39,
                "status":"Belum Diketahui",
                "kota":"Sabang"
            },
            {
                "id":"5e91c56468edc03c5d70e737",
                "nama":"Ramirez Maxwell",
                "umur":74,
                "status":"Negatif",
                "kota":"Tarakan"
            },
            {
                "id":"5e91c5640dbdee61d87ce02a",
                "nama":"Terra Aguirre",
                "umur":79,
                "status":"Negatif",
                "kota":"Metro"
            },
            {
                "id":"5e91c5645c6601167b54859c",
                "nama":"Cardenas Love",
                "umur":14,
                "status":"Belum Diketahui",
                "kota":"Denpasar"
            },
            {
                "id":"5e91c564fdb5a543ea5ed9dc",
                "nama":"Puckett Gould",
                "umur":10,
                "status":"Positif",
                "kota":"Batam"
            },
            {
                "id":"5e91c56416a82381ff5b0b20",
                "nama":"Cindy Cardenas",
                "umur":77,
                "status":"Negatif",
                "kota":"Surabaya"
            },
            {
                "id":"5e91c564572e698d4068d44f",
                "nama":"Hardy Spence",
                "umur":94,
                "status":"Positif",
                "kota":"Tual"
            },
            {
                "id":"5e91c5647b42f409d47867e4",
                "nama":"Augusta Schneider",
                "umur":45,
                "status":"Belum Diketahui",
                "kota":"Pematangsiantar"
            },
            {
                "id":"5e91c564530ce370e8ee2e43",
                "nama":"Peters Nieves",
                "umur":52,
                "status":"Belum Diketahui",
                "kota":"Ambon"
            },
            {
                "id":"5e91c564aaf2532c49392f89",
                "nama":"Richard Shelton",
                "umur":94,
                "status":"Positif",
                "kota":"Jambi"
            },
            {
                "id":"5e91c5640a23709b454fb03f",
                "nama":"Kelsey Contreras",
                "umur":77,
                "status":"Negatif",
                "kota":"Pontianak"
            },
            {
                "id":"5e91c564719239adaac65ac0",
                "nama":"Evangelina Diaz",
                "umur":52,
                "status":"Belum Diketahui",
                "kota":"Palopo"
            },
            {
                "id":"5e91c564a388461464a6d780",
                "nama":"Norman Boyer",
                "umur":47,
                "status":"Belum Diketahui",
                "kota":"Tarakan"
            },
            {
                "id":"5e91c5644790483756f9a95f",
                "nama":"Jessie Allen",
                "umur":82,
                "status":"Belum Diketahui",
                "kota":"Jakarta Selatan"
            },
            {
                "id":"5e91c564b837474f9b350e3f",
                "nama":"Autumn Bennett",
                "umur":99,
                "status":"Positif",
                "kota":"Cilegon"
            },
            {
                "id":"5e91c564ef44703942deabb1",
                "nama":"Chavez Navarro",
                "umur":4,
                "status":"Positif",
                "kota":"Binjai"
            },
            {
                "id":"5e91c564423a4b176c1f6b4d",
                "nama":"Magdalena Hickman",
                "umur":16,
                "status":"Belum Diketahui",
                "kota":"Gorontalo"
            },
            {
                "id":"5e91c5649f7f552e1cbe5fa1",
                "nama":"Kathy Conner",
                "umur":63,
                "status":"Negatif",
                "kota":"Ambon"
            },
            {
                "id":"5e91c564c1c0f2a1711944a1",
                "nama":"Bean Singleton",
                "umur":99,
                "status":"Belum Diketahui",
                "kota":"Tanjungpinang"
            },
            {
                "id":"5e91c5649c7b419fa568214c",
                "nama":"Marianne Stuart",
                "umur":7,
                "status":"Positif",
                "kota":"Tanjungbalai"
            },
            {
                "id":"5e91c5646bf6883d72a0382c",
                "nama":"Daugherty Acevedo",
                "umur":38,
                "status":"Negatif",
                "kota":"Bitung"
            },
            {
                "id":"5e91c56406971e26dad31938",
                "nama":"Latonya Burgess",
                "umur":91,
                "status":"Belum Diketahui",
                "kota":"Subulussalam"
            },
            {
                "id":"5e91c564d79dc63dc89d6b38",
                "nama":"Tabatha Burke",
                "umur":55,
                "status":"Belum Diketahui",
                "kota":"Subulussalam"
            },
            {
                "id":"5e91c564502c2c85f63b0815",
                "nama":"Martina Bray",
                "umur":91,
                "status":"Positif",
                "kota":"Makassar"
            },
            {
                "id":"5e91c564e5c2ee9f342ba112",
                "nama":"Allison Curtis",
                "umur":25,
                "status":"Positif",
                "kota":"Sorong"
            },
            {
                "id":"5e91c5640e0434e4acdc7d09",
                "nama":"Lorene Odonnell",
                "umur":20,
                "status":"Positif",
                "kota":"Tanjungbalai"
            },
            {
                "id":"5e91c564c51421d08c1ca8d2",
                "nama":"Tammi Bradley",
                "umur":64,
                "status":"Negatif",
                "kota":"Bogo"
            },
            {
                "id":"5e91c5649d6b6e100077b0fe",
                "nama":"Elvia Rosales",
                "umur":89,
                "status":"Belum Diketahui",
                "kota":"Balikpapan"
            },
            {
                "id":"5e91c5649651e7d4a99003c8",
                "nama":"Marjorie Bowers",
                "umur":49,
                "status":"Belum Diketahui",
                "kota":"Tomohon"
            },
            {
                "id":"5e91c564cf17765ec59e42fd",
                "nama":"Pearson Douglas",
                "umur":42,
                "status":"Positif",
                "kota":"Bitung"
            },
            {
                "id":"5e91c56472429013846cb902",
                "nama":"Valdez Vega",
                "umur":10,
                "status":"Belum Diketahui",
                "kota":"Binjai"
            },
            {
                "id":"5e91c56401cfcd892ecf392a",
                "nama":"Nichols Reeves",
                "umur":59,
                "status":"Negatif",
                "kota":"Tomohon"
            },
            {
                "id":"5e91c56442dccfc5bc4c3922",
                "nama":"Felicia Thornton",
                "umur":100,
                "status":"Belum Diketahui",
                "kota":"Meulaboh"
            },
            {
                "id":"5e91c56470a78f541ad7692b",
                "nama":"Mary Kim",
                "umur":27,
                "status":"Negatif",
                "kota":"Lhokseumawe"
            },
            {
                "id":"5e91c56418e78913a132e5f9",
                "nama":"Madelyn Cross",
                "umur":62,
                "status":"Negatif",
                "kota":"Bau-Bau"
            },
            {
                "id":"5e91c564fef89196930f204c",
                "nama":"Jenkins Mccarthy",
                "umur":97,
                "status":"Belum Diketahui",
                "kota":"Balikpapan"
            },
            {
                "id":"5e91c5648919478cf4b76212",
                "nama":"Dionne Decker",
                "umur":1,
                "status":"Belum Diketahui",
                "kota":"Bima"
            },
            {
                "id":"5e91c564fdae750ad08cd25d",
                "nama":"Erma Estes",
                "umur":63,
                "status":"Negatif",
                "kota":"Lhokseumawe"
            },
            {
                "id":"5e91c56406a5ab551756488b",
                "nama":"Gould Washington",
                "umur":20,
                "status":"Positif",
                "kota":"Lubuklinggau"
            },
            {
                "id":"5e91c56477b1cda741d9f379",
                "nama":"Jane Bullock",
                "umur":48,
                "status":"Positif",
                "kota":"Samarinda"
            },
            {
                "id":"5e91c5645eb4d48287d3f84d",
                "nama":"Alexis Bush",
                "umur":64,
                "status":"Positif",
                "kota":"Banjarbaru"
            },
            {
                "id":"5e91c564c97d252bdae223dc",
                "nama":"Pickett Phillips",
                "umur":72,
                "status":"Positif",
                "kota":"Manado"
            },
            {
                "id":"5e91c56424ab09b539fa6cd2",
                "nama":"Kristina Fields",
                "umur":60,
                "status":"Belum Diketahui",
                "kota":"Palembang"
            },
            {
                "id":"5e91c56486c5e77ff2a1d55a",
                "nama":"Herring Reed",
                "umur":2,
                "status":"Negatif",
                "kota":"Cilegon"
            },
            {
                "id":"5e91c56416e978dfdae5ae25",
                "nama":"Cooke Bird",
                "umur":78,
                "status":"Negatif",
                "kota":"Tangerang"
            },
            {
                "id":"5e91c56415a5cf521f337564",
                "nama":"Lydia Lancaster",
                "umur":69,
                "status":"Positif",
                "kota":"Surabaya"
            },
            {
                "id":"5e91c5643d8963696ec674fc",
                "nama":"Louisa Cleveland",
                "umur":8,
                "status":"Negatif",
                "kota":"Padangpanjang"
            },
            {
                "id":"5e91c56422badb51524e403b",
                "nama":"Merritt Newman",
                "umur":1,
                "status":"Belum Diketahui",
                "kota":"Aceh"
            },
            {
                "id":"5e91c564a86c51cfbfefa187",
                "nama":"Lawanda Madden",
                "umur":53,
                "status":"Positif",
                "kota":"Cirebon"
            },
            {
                "id":"5e91c564ab94e82188a78ba7",
                "nama":"Whitaker White",
                "umur":68,
                "status":"Negatif",
                "kota":"Jayapura"
            },
            {
                "id":"5e91c564d76557cc4e291a96",
                "nama":"Margret Kaufman",
                "umur":91,
                "status":"Positif",
                "kota":"Bandung"
            },
            {
                "id":"5e91c564e9b3dc6505111823",
                "nama":"Dunlap Henderson",
                "umur":68,
                "status":"Negatif",
                "kota":"Surakarta"
            },
            {
                "id":"5e91c5645bbbf7eb19138a1c",
                "nama":"Adela Meadows",
                "umur":45,
                "status":"Belum Diketahui",
                "kota":"Palembang"
            },
            {
                "id":"5e91c564b1f018401cf3a474",
                "nama":"Barber Reese",
                "umur":54,
                "status":"Negatif",
                "kota":"Pekanbaru"
            },
            {
                "id":"5e91c564155957db79cbdf3e",
                "nama":"Alford Rich",
                "umur":100,
                "status":"Positif",
                "kota":"Dumai"
            },
            {
                "id":"5e91c5642433415cc3ae37f5",
                "nama":"Moss Woods",
                "umur":74,
                "status":"Positif",
                "kota":"Palu"
            },
            {
                "id":"5e91c564d0df403a76bfea7c",
                "nama":"Silvia Petty",
                "umur":37,
                "status":"Belum Diketahui",
                "kota":"Singkawang"
            },
            {
                "id":"5e91c564414bf784477d9362",
                "nama":"Nolan Klein",
                "umur":29,
                "status":"Negatif",
                "kota":"Pasuruan"
            },
            {
                "id":"5e91c564e3c37b0c83cfea0e",
                "nama":"Berry Martin",
                "umur":23,
                "status":"Positif",
                "kota":"Madiun"
            },
            {
                "id":"5e91c5641143e4f7f018465a",
                "nama":"Moore Burch",
                "umur":97,
                "status":"Positif",
                "kota":"Sungai Penuh"
            },
            {
                "id":"5e91c564ef3ed1c2849dc3fc",
                "nama":"Todd Charles",
                "umur":17,
                "status":"Positif",
                "kota":"Singkawang"
            },
            {
                "id":"5e91c5644b312d06ff42c4ed",
                "nama":"Callie Case",
                "umur":58,
                "status":"Belum Diketahui",
                "kota":"Gorontalo"
            },
            {
                "id":"5e91c564964938e3683d531b",
                "nama":"Nikki Mendez",
                "umur":16,
                "status":"Belum Diketahui",
                "kota":"Kendari"
            },
            {
                "id":"5e91c5649d51f04b5eba539c",
                "nama":"Yang Vang",
                "umur":100,
                "status":"Positif",
                "kota":"Yogyakarta"
            },
            {
                "id":"5e91c564b404ca8a03c8b3fd",
                "nama":"Hester Sharp",
                "umur":70,
                "status":"Positif",
                "kota":"Gorontalo"
            },
            {
                "id":"5e91c5649ad352cae2facdf9",
                "nama":"Goldie Fletcher",
                "umur":64,
                "status":"Negatif",
                "kota":"Pontianak"
            },
            {
                "id":"5e91c564e3ced2ed86a43439",
                "nama":"Gonzalez Norman",
                "umur":47,
                "status":"Negatif",
                "kota":"Ternate"
            },
            {
                "id":"5e91c564e2ab1390dab26808",
                "nama":"Mathews Paul",
                "umur":53,
                "status":"Negatif",
                "kota":"Jakarta Pusat"
            },
            {
                "id":"5e91c5649f8413d373db4e76",
                "nama":"Luella Morris",
                "umur":45,
                "status":"Negatif",
                "kota":"Kotamobagu"
            },
            {
                "id":"5e91c564d7a0635b63a559dd",
                "nama":"Eileen Gonzales",
                "umur":25,
                "status":"Belum Diketahui",
                "kota":"Jakarta Timur"
            },
            {
                "id":"5e91c564ed24261285db5c8f",
                "nama":"Sheena Abbott",
                "umur":65,
                "status":"Belum Diketahui",
                "kota":"Pekanbaru"
            },
            {
                "id":"5e91c5642fe0810f7cb5922a",
                "nama":"Bertie Parsons",
                "umur":50,
                "status":"Negatif",
                "kota":"Banjarmasi"
            },
            {
                "id":"5e91c56475ea150e68adc172",
                "nama":"Jackson Ray",
                "umur":66,
                "status":"Negatif",
                "kota":"Bandung"
            },
            {
                "id":"5e91c5641c3baa7e0ed5afee",
                "nama":"Helen Montoya",
                "umur":58,
                "status":"Positif",
                "kota":"Lhokseumawe"
            },
            {
                "id":"5e91c564cb5a88ae20440b06",
                "nama":"Marguerite Adkins",
                "umur":94,
                "status":"Belum Diketahui",
                "kota":"Sawahlunto"
            }
        ]
