# Sekolah FE

Daftar Pasien

## Get Patient List [/patient-list]
### Get All Patient List [GET]
+ Response 200 (application/json)

        [
            {
                "id":"5e93278fe01f0cb89d2d4776",
                "nama":"Aguilar Hughes",
                "umur":48,
                "status":"Belum Diketahui",
                "kota":"Gorontalo"
            },
            {
                "id":"5e93278fff431cb221cc8223",
                "nama":"Madden Maxwell",
                "umur":55,
                "status":"Positif",
                "kota":"Madiun"
            },
            {
                "id":"5e93278f1129ce2adc0d0876",
                "nama":"Mooney Weber",
                "umur":80,
                "status":"Belum Diketahui",
                "kota":"Tangerang Selatan"
            },
            {
                "id":"5e93278f7ef3d239339ef7e1",
                "nama":"Ball Castillo",
                "umur":53,
                "status":"Belum Diketahui",
                "kota":"Denpasar"
            },
            {
                "id":"5e93278f9e1b8e841ffc0282",
                "nama":"Melva Hamilton",
                "umur":42,
                "status":"Negatif",
                "kota":"Tebingtinggi"
            },
            {
                "id":"5e93278f14e6842dac03dabf",
                "nama":"Colon Wright",
                "umur":37,
                "status":"Positif",
                "kota":"Solok"
            },
            {
                "id":"5e93278f3ac99f938b7ffd1b",
                "nama":"Jana Allison",
                "umur":42,
                "status":"Positif",
                "kota":"Tual"
            },
            {
                "id":"5e93278fee1b71b8fe6c37e3",
                "nama":"Macias Conrad",
                "umur":21,
                "status":"Positif",
                "kota":"Tual"
            },
            {
                "id":"5e93278f5bcd744731f2231d",
                "nama":"Linda Mcgowan",
                "umur":50,
                "status":"Belum Diketahui",
                "kota":"Gorontalo"
            },
            {
                "id":"5e93278fceaca4b513b33e99",
                "nama":"Inez Nichols",
                "umur":26,
                "status":"Negatif",
                "kota":"Tasikmalay"
            },
            {
                "id":"5e93278ff1d6fd6650fd7d6a",
                "nama":"Lily Barlow",
                "umur":71,
                "status":"Positif",
                "kota":"Surabaya"
            },
            {
                "id":"5e93278ff266b0bce1161b3b",
                "nama":"Noreen French",
                "umur":80,
                "status":"Belum Diketahui",
                "kota":"Pagaralam"
            },
            {
                "id":"5e93278feb5e17af141e5370",
                "nama":"Gould Chaney",
                "umur":55,
                "status":"Belum Diketahui",
                "kota":"Magelang"
            },
            {
                "id":"5e93278ffbd404b656d80d1c",
                "nama":"Middleton Shelton",
                "umur":28,
                "status":"Belum Diketahui",
                "kota":"Aceh"
            },
            {
                "id":"5e93278f1b7d021776deb725",
                "nama":"Ayers Lawrence",
                "umur":46,
                "status":"Belum Diketahui",
                "kota":"Sabang"
            },
            {
                "id":"5e93278f43ae54e4d1df3235",
                "nama":"Viola Guthrie",
                "umur":75,
                "status":"Belum Diketahui",
                "kota":"Subulussalam"
            },
            {
                "id":"5e93278fa5eac42780261a0c",
                "nama":"Wallace Townsend",
                "umur":46,
                "status":"Negatif",
                "kota":"Sorong"
            },
            {
                "id":"5e93278fa72f731fedc2a0cb",
                "nama":"Rhea Potter",
                "umur":58,
                "status":"Negatif",
                "kota":"Batam"
            },
            {
                "id":"5e93278f340e19182ed73a41",
                "nama":"Cortez Goff",
                "umur":43,
                "status":"Negatif",
                "kota":"Padangpanjang"
            },
            {
                "id":"5e93278f4cb4fed4781a19fb",
                "nama":"Neal Humphrey",
                "umur":41,
                "status":"Positif",
                "kota":"Blitar"
            },
            {
                "id":"5e93278fceea9c69730b391a",
                "nama":"Leila Lopez",
                "umur":65,
                "status":"Positif",
                "kota":"Langsa"
            },
            {
                "id":"5e93278f839d961bd4229bf3",
                "nama":"Wilkins Peck",
                "umur":48,
                "status":"Belum Diketahui",
                "kota":"Batam"
            },
            {
                "id":"5e93278ff26bf3be10224d93",
                "nama":"Giles Pace",
                "umur":75,
                "status":"Negatif",
                "kota":"Cilegon"
            },
            {
                "id":"5e93278f6f7508ca75ff7936",
                "nama":"Hazel Atkinson",
                "umur":63,
                "status":"Negatif",
                "kota":"Kendari"
            },
            {
                "id":"5e93278f0821e7baf61ee4c3",
                "nama":"Marisa Cross",
                "umur":48,
                "status":"Belum Diketahui",
                "kota":"Cimahi"
            },
            {
                "id":"5e93278f5ce8981df99b16b4",
                "nama":"Nola Burnett",
                "umur":61,
                "status":"Belum Diketahui",
                "kota":"Gorontalo"
            },
            {
                "id":"5e93278f7ee6dbaffc2e54b0",
                "nama":"Jerry Sanchez",
                "umur":60,
                "status":"Negatif",
                "kota":"Pematangsiantar"
            },
            {
                "id":"5e93278f8bbcff594150e639",
                "nama":"Mcintosh Robles",
                "umur":51,
                "status":"Positif",
                "kota":"Cimahi"
            },
            {
                "id":"5e93278f00885351ff3cc61e",
                "nama":"Cunningham Rush",
                "umur":20,
                "status":"Positif",
                "kota":"Makassar"
            },
            {
                "id":"5e93278fbda09b7a1276d2d3",
                "nama":"Vang Hoover",
                "umur":28,
                "status":"Belum Diketahui",
                "kota":"Metro"
            },
            {
                "id":"5e93278f785a2b4b7941ac8a",
                "nama":"Alma Ortega",
                "umur":28,
                "status":"Negatif",
                "kota":"Banjarbaru"
            },
            {
                "id":"5e93278fd002fad4a7c23082",
                "nama":"Kathy Dudley",
                "umur":60,
                "status":"Negatif",
                "kota":"Banjarmasi"
            },
            {
                "id":"5e93278fd5a895878f76d9e0",
                "nama":"Simmons Powell",
                "umur":21,
                "status":"Negatif",
                "kota":"Palopo"
            },
            {
                "id":"5e93278f662babcf5b8dadf4",
                "nama":"Samantha Mcdonald",
                "umur":46,
                "status":"Negatif",
                "kota":"Meulaboh"
            },
            {
                "id":"5e93278f6a8c5a7a51ef3fbb",
                "nama":"Glenn Baird",
                "umur":44,
                "status":"Belum Diketahui",
                "kota":"Bengkulu"
            },
            {
                "id":"5e93278f2c0df034eeaf39d9",
                "nama":"David Browning",
                "umur":12,
                "status":"Positif",
                "kota":"Denpasar"
            },
            {
                "id":"5e93278f97fd24e6de343670",
                "nama":"Danielle Cohen",
                "umur":64,
                "status":"Positif",
                "kota":"Pematangsiantar"
            },
            {
                "id":"5e93278fa9cbcfe60fa511a5",
                "nama":"Jacobs Reese",
                "umur":58,
                "status":"Belum Diketahui",
                "kota":"Bontang"
            },
            {
                "id":"5e93278ffac7df683267106d",
                "nama":"Lawanda Gardner",
                "umur":21,
                "status":"Negatif",
                "kota":"Denpasar"
            },
            {
                "id":"5e93278f30c08672f11cdb7d",
                "nama":"Stephens Duran",
                "umur":71,
                "status":"Negatif",
                "kota":"Palu"
            },
            {
                "id":"5e93278f0fcdc96c70b1f7e7",
                "nama":"Sharp Holder",
                "umur":48,
                "status":"Negatif",
                "kota":"Pekanbaru"
            },
            {
                "id":"5e93278f1b8b6548b25862ad",
                "nama":"Amalia Cervantes",
                "umur":46,
                "status":"Belum Diketahui",
                "kota":"Cilegon"
            },
            {
                "id":"5e93278fa54d8146f9f802a3",
                "nama":"Alexis Mcknight",
                "umur":58,
                "status":"Belum Diketahui",
                "kota":"Banjar"
            },
            {
                "id":"5e93278f97f59ae9f6caf364",
                "nama":"Wise Savage",
                "umur":66,
                "status":"Negatif",
                "kota":"Pekanbaru"
            },
            {
                "id":"5e93278f3d8e56f4ebebe58e",
                "nama":"Barry Rich",
                "umur":46,
                "status":"Positif",
                "kota":"Kendari"
            },
            {
                "id":"5e93278fa3e6c89ecda3b78f",
                "nama":"Harris Charles",
                "umur":36,
                "status":"Positif",
                "kota":"Kotamobagu"
            },
            {
                "id":"5e93278f73ca20dfab975991",
                "nama":"Kelly Spears",
                "umur":54,
                "status":"Belum Diketahui",
                "kota":"Salatiga"
            },
            {
                "id":"5e93278f92eb8da6165a5ed4",
                "nama":"Leonor Walker",
                "umur":12,
                "status":"Negatif",
                "kota":"Tarakan"
            },
            {
                "id":"5e93278f3ff2cdd7227e62c9",
                "nama":"Susana Bailey",
                "umur":28,
                "status":"Positif",
                "kota":"Sawahlunto"
            },
            {
                "id":"5e93278f6ec9c652c08ea11a",
                "nama":"Selma Bentley",
                "umur":44,
                "status":"Negatif",
                "kota":"Padangpanjang"
            },
            {
                "id":"5e93278f0df1e9ffe0a8db4d",
                "nama":"Chen Butler",
                "umur":61,
                "status":"Negatif",
                "kota":"Jakarta Timur"
            },
            {
                "id":"5e93278fbbdc15d67190ef65",
                "nama":"Violet Day",
                "umur":13,
                "status":"Positif",
                "kota":"Madiun"
            },
            {
                "id":"5e93278fe6bb733ae994423b",
                "nama":"Gibbs Bennett",
                "umur":38,
                "status":"Belum Diketahui",
                "kota":"Balikpapan"
            },
            {
                "id":"5e93278f03d42ce91f4f8606",
                "nama":"Evangelina Schmidt",
                "umur":62,
                "status":"Negatif",
                "kota":"Kotamobagu"
            },
            {
                "id":"5e93278f94390de86dca6835",
                "nama":"English Tyson",
                "umur":55,
                "status":"Positif",
                "kota":"Pekanbaru"
            },
            {
                "id":"5e93278fa73ae07ebbc015f0",
                "nama":"Roach Odom",
                "umur":47,
                "status":"Negatif",
                "kota":"Sawahlunto"
            },
            {
                "id":"5e93278f20c2563ec56883cc",
                "nama":"Hester Garrett",
                "umur":54,
                "status":"Negatif",
                "kota":"Probolinggo"
            },
            {
                "id":"5e93278f4bbff876515ce44a",
                "nama":"Nell Chambers",
                "umur":16,
                "status":"Belum Diketahui",
                "kota":"Ternate"
            },
            {
                "id":"5e93278fcf195168f6697af0",
                "nama":"Estes Marquez",
                "umur":63,
                "status":"Belum Diketahui",
                "kota":"Banjarmasi"
            },
            {
                "id":"5e93278f03e085705ec7152c",
                "nama":"Merle Wall",
                "umur":62,
                "status":"Belum Diketahui",
                "kota":"Malang"
            },
            {
                "id":"5e93278fb5f6be24aa900ae5",
                "nama":"Higgins Elliott",
                "umur":19,
                "status":"Positif",
                "kota":"Bima"
            },
            {
                "id":"5e93278fd9ed9c0df56b9957",
                "nama":"Etta Oneil",
                "umur":60,
                "status":"Negatif",
                "kota":"Padangpanjang"
            },
            {
                "id":"5e93278fe6ddb7202ddc0906",
                "nama":"Trina Brooks",
                "umur":74,
                "status":"Belum Diketahui",
                "kota":"Bau-Bau"
            },
            {
                "id":"5e93278f1ccc2741de6e3a95",
                "nama":"Keith Carrillo",
                "umur":52,
                "status":"Positif",
                "kota":"Depok"
            },
            {
                "id":"5e93278f6c8c42d354aea29a",
                "nama":"Moses Curry",
                "umur":14,
                "status":"Belum Diketahui",
                "kota":"Sukabumi"
            },
            {
                "id":"5e93278fed01db4dd8448f2c",
                "nama":"Shepherd Cook",
                "umur":21,
                "status":"Positif",
                "kota":"Prabumulih"
            },
            {
                "id":"5e93278fe483fc87b4ad992d",
                "nama":"Lupe West",
                "umur":46,
                "status":"Negatif",
                "kota":"Jambi"
            },
            {
                "id":"5e93278fafa97189d284d85d",
                "nama":"Lucy Diaz",
                "umur":19,
                "status":"Negatif",
                "kota":"Salatiga"
            },
            {
                "id":"5e93278f85556b01d53833fd",
                "nama":"Hilda Skinner",
                "umur":44,
                "status":"Positif",
                "kota":"Bandung"
            },
            {
                "id":"5e93278f80aa315388798fcc",
                "nama":"Latoya Guerra",
                "umur":48,
                "status":"Negatif",
                "kota":"Padangpanjang"
            },
            {
                "id":"5e93278fa7859545371bdcc1",
                "nama":"Woodard Keller",
                "umur":38,
                "status":"Negatif",
                "kota":"Jambi"
            },
            {
                "id":"5e93278f724d47fa9deb865f",
                "nama":"Sykes Carter",
                "umur":33,
                "status":"Belum Diketahui",
                "kota":"Purwokerto"
            },
            {
                "id":"5e93278fd3082ce4c8290f2a",
                "nama":"Tyson Clarke",
                "umur":41,
                "status":"Positif",
                "kota":"Palangkaraya"
            },
            {
                "id":"5e93278f8fb896536229fd57",
                "nama":"Dyer Galloway",
                "umur":54,
                "status":"Positif",
                "kota":"Purwokerto"
            },
            {
                "id":"5e93278fd10c876679869e71",
                "nama":"Marks Bartlett",
                "umur":68,
                "status":"Belum Diketahui",
                "kota":"Cilegon"
            },
            {
                "id":"5e93278f6e4b4ce0e406862c",
                "nama":"Leigh Morse",
                "umur":72,
                "status":"Positif",
                "kota":"Kediri"
            },
            {
                "id":"5e93278ffd42e67486d72f95",
                "nama":"Keller Eaton",
                "umur":49,
                "status":"Negatif",
                "kota":"Aceh"
            },
            {
                "id":"5e93278f7383a271135fc73b",
                "nama":"Gallagher Mooney",
                "umur":20,
                "status":"Negatif",
                "kota":"Makassar"
            },
            {
                "id":"5e93278fdba2093018fca5ac",
                "nama":"Beasley Riley",
                "umur":57,
                "status":"Positif",
                "kota":"Pematangsiantar"
            },
            {
                "id":"5e93278f743b53d105de1b6b",
                "nama":"Mavis Harper",
                "umur":11,
                "status":"Belum Diketahui",
                "kota":"Sibolga"
            },
            {
                "id":"5e93278f99548fd4027db926",
                "nama":"Jane Wilcox",
                "umur":48,
                "status":"Negatif",
                "kota":"Bitung"
            },
            {
                "id":"5e93278f7679afeaeef7f84a",
                "nama":"Beck Mueller",
                "umur":80,
                "status":"Positif",
                "kota":"Bandung"
            },
            {
                "id":"5e93278f2d43d8c0e628fab7",
                "nama":"Wendy Hawkins",
                "umur":24,
                "status":"Belum Diketahui",
                "kota":"Pekanbaru"
            },
            {
                "id":"5e93278ff31d9684d3ac0b93",
                "nama":"Eva Sullivan",
                "umur":38,
                "status":"Belum Diketahui",
                "kota":"Jakarta Pusat"
            },
            {
                "id":"5e93278f7e917010bfa08562",
                "nama":"Mollie Banks",
                "umur":24,
                "status":"Belum Diketahui",
                "kota":"Yogyakarta"
            },
            {
                "id":"5e93278f42974f30dbf23ed5",
                "nama":"Lopez Leonard",
                "umur":39,
                "status":"Negatif",
                "kota":"Blitar"
            },
            {
                "id":"5e93278faf0b2a951bc1a12c",
                "nama":"Alexandria Spence",
                "umur":56,
                "status":"Positif",
                "kota":"Tanjungbalai"
            },
            {
                "id":"5e93278f1b4c4ff8e29552bb",
                "nama":"Luisa Alexander",
                "umur":56,
                "status":"Negatif",
                "kota":"Bengkulu"
            },
            {
                "id":"5e93278fa3c25823bb30cafc",
                "nama":"Riddle Wolfe",
                "umur":73,
                "status":"Negatif",
                "kota":"Sorong"
            },
            {
                "id":"5e93278fa6f5c31d3c1323ef",
                "nama":"Billie Mays",
                "umur":72,
                "status":"Belum Diketahui",
                "kota":"Bukittinggi"
            },
            {
                "id":"5e93278f2b83ca8a765bf7b0",
                "nama":"Rosales Kirk",
                "umur":23,
                "status":"Negatif",
                "kota":"Surakarta"
            },
            {
                "id":"5e93278fd1173c99a4bfb577",
                "nama":"Short Clements",
                "umur":13,
                "status":"Belum Diketahui",
                "kota":"Aceh"
            },
            {
                "id":"5e93278fdcac48188e572be2",
                "nama":"Taylor Dodson",
                "umur":13,
                "status":"Negatif",
                "kota":"Batu"
            },
            {
                "id":"5e93278f2c81573220a30c68",
                "nama":"Flynn Bullock",
                "umur":64,
                "status":"Belum Diketahui",
                "kota":"Tomohon"
            },
            {
                "id":"5e93278f4051c8b6441e483a",
                "nama":"Melissa Rhodes",
                "umur":43,
                "status":"Belum Diketahui",
                "kota":"Padang Sidempuan"
            },
            {
                "id":"5e93278ff0cf1d81ca169295",
                "nama":"Carmella Good",
                "umur":69,
                "status":"Belum Diketahui",
                "kota":"Kupang"
            },
            {
                "id":"5e93278f927f8ed4f0955b23",
                "nama":"Stacy Patel",
                "umur":77,
                "status":"Positif",
                "kota":"Ternate"
            },
            {
                "id":"5e93278ffe3c1dc790688fa9",
                "nama":"Atkins Perry",
                "umur":29,
                "status":"Belum Diketahui",
                "kota":"Bogo"
            },
            {
                "id":"5e93278f6614d2062c7b6937",
                "nama":"Georgette Chan",
                "umur":48,
                "status":"Positif",
                "kota":"Tarakan"
            },
            {
                "id":"5e93278f05e9f9de61da8903",
                "nama":"Murray Buck",
                "umur":54,
                "status":"Negatif",
                "kota":"Probolinggo"
            }
        ]

## Get City List [/city-list]
### Get All City List [GET]
+ Response 200 (application/json)

        [
            "Aceh",
            "Langsa",
            "Lhokseumawe",
            "Meulaboh",
            "Sabang",
            "Subulussalam",
            "Denpasar",
            "Belitung",
            "Cilegon",
            "Serang",
            "Tangerang Selatan",
            "Tangerang",
            "Bengkulu",
            "Gorontalo",
            "Jakarta Barat",
            "Jakarta Pusat",
            "Jakarta Selatan",
            "Jakarta Timur",
            "Jakarta Utara",
            "Sungai Penuh",
            "Jambi",
            "Bandung",
            "Bekasi",
            "Bogo",
            "Cimahi",
            "Cirebon",
            "Depok",
            "Sukabumi",
            "Tasikmalay",
            "Banjar",
            "Magelang",
            "Pekalongan",
            "Purwokerto",
            "Salatiga",
            "Semarang",
            "Surakarta",
            "Tegal",
            "Batu",
            "Blitar",
            "Kediri",
            "Madiun",
            "Malang",
            "Mojokerto",
            "Pasuruan",
            "Probolinggo",
            "Surabaya",
            "Pontianak",
            "Singkawang",
            "Banjarbaru",
            "Banjarmasi",
            "Palangkaraya",
            "Balikpapan",
            "Bontang",
            "Samarinda",
            "Tarakan",
            "Batam",
            "Tanjungpinang",
            "Lampung",
            "Metro",
            "Ternate",
            "Tidore",
            "Ambon",
            "Tual",
            "Bima",
            "Mataram",
            "Kupang",
            "Sorong",
            "Jayapura",
            "Dumai",
            "Pekanbaru",
            "Makassar",
            "Palopo",
            "Parepare",
            "Palu",
            "Bau-Bau",
            "Kendari",
            "Bitung",
            "Kotamobagu",
            "Manado",
            "Tomohon",
            "Bukittinggi",
            "Padang",
            "Padangpanjang",
            "Pariaman",
            "Payakumbuh",
            "Sawahlunto",
            "Solok",
            "Lubuklinggau",
            "Pagaralam",
            "Palembang",
            "Prabumulih",
            "Binjai",
            "Medan",
            "Padang Sidempuan",
            "Pematangsiantar",
            "Sibolga",
            "Tanjungbalai",
            "Tebingtinggi",
            "Yogyakarta"
        ]

## Get Patient Status List [/patient-status-list]
### Get All Patient Status List [GET]
+ Response 200 (application/json)

        [
            "Positif",
            "Negatif",
            "Belum Diketahui"
        ]
