# Sekolah FE

## Patient [/patient-list]
### Get Patient List [GET]
+ Response 200 (application/json)

        [
            {
                "id": 1423895298,
                "nama": "Felecia Frost",
                "umur": 15,
                "status": "Positif",
                "kota": "Jakarta Timur"
            },
            {
                "id": 1438592663,
                "nama": "Fleming Palmer",
                "umur": 16,
                "status": "Negatif",
                "kota": "Yogyakarta"
            },
            {
                "id": 1392212988,
                "nama": "Bass Ferrell",
                "umur": 18,
                "status": "Negatif",
                "kota": "Bandung"
            },
            {
                "id": 1438576508,
                "nama": "Sheri Cooke",
                "umur": 33,
                "status": "Belum Diketahui",
                "kota": "Pariaman"
            },
            {
                "id": 1564522759,
                "nama": "Kimberly Frederick",
                "umur": 80,
                "status": "Belum Diketahui",
                "kota": "Magelang"
            },
            {
                "id": 1470906774,
                "nama": "Stokes Curry",
                "umur": 26,
                "status": "Negatif",
                "kota": "Yogyakarta"
            },
            {
                "id": 1514927955,
                "nama": "Louisa Barrera",
                "umur": 34,
                "status": "Negatif",
                "kota": "Surabaya"
            },
            {
                "id": 1563174673,
                "nama": "Bryan Neal",
                "umur": 44,
                "status": "Positif",
                "kota": "Balikpapan"
            },
            {
                "id": 1508509461,
                "nama": "Browning Gutierrez",
                "umur": 42,
                "status": "Negatif",
                "kota": "Kotamobagu"
            },
            {
                "id": 1441274492,
                "nama": "Peterson Payne",
                "umur": 17,
                "status": "Belum Diketahui",
                "kota": "Tarakan"
            },
            {
                "id": 1587111602,
                "nama": "Brandy Mcgee",
                "umur": 26,
                "status": "Negatif",
                "kota": "Palangkaraya"
            },
            {
                "id": 1517709306,
                "nama": "Hobbs Spence",
                "umur": 66,
                "status": "Negatif",
                "kota": "Parepare"
            },
            {
                "id": 1473375342,
                "nama": "Ford English",
                "umur": 53,
                "status": "Belum Diketahui",
                "kota": "Bitung"
            },
            {
                "id": 1446407068,
                "nama": "Leon Ford",
                "umur": 24,
                "status": "Negatif",
                "kota": "Bukittinggi"
            },
            {
                "id": 1542309267,
                "nama": "Christi Carpenter",
                "umur": 62,
                "status": "Positif",
                "kota": "Pasuruan"
            },
            {
                "id": 1438548242,
                "nama": "Jamie Cash",
                "umur": 32,
                "status": "Positif",
                "kota": "Tanjungbalai"
            },
            {
                "id": 1511462838,
                "nama": "Delacruz Harrington",
                "umur": 78,
                "status": "Belum Diketahui",
                "kota": "Sibolga"
            },
            {
                "id": 1397755236,
                "nama": "Talley Munoz",
                "umur": 36,
                "status": "Positif",
                "kota": "Palembang"
            },
            {
                "id": 1501702198,
                "nama": "Polly Copeland",
                "umur": 15,
                "status": "Positif",
                "kota": "Padang Sidempuan"
            },
            {
                "id": 1527552200,
                "nama": "Lisa Guthrie",
                "umur": 79,
                "status": "Belum Diketahui",
                "kota": "Palopo"
            },
            {
                "id": 1390402893,
                "nama": "Sheryl Hale",
                "umur": 46,
                "status": "Negatif",
                "kota": "Surabaya"
            },
            {
                "id": 1570359438,
                "nama": "Hampton Barton",
                "umur": 29,
                "status": "Negatif",
                "kota": "Bima"
            },
            {
                "id": 1471116224,
                "nama": "Randi Lindsay",
                "umur": 67,
                "status": "Belum Diketahui",
                "kota": "Serang"
            },
            {
                "id": 1584331730,
                "nama": "April Jacobs",
                "umur": 64,
                "status": "Positif",
                "kota": "Pematangsiantar"
            },
            {
                "id": 1499834315,
                "nama": "Gardner Barr",
                "umur": 34,
                "status": "Positif",
                "kota": "Bogo"
            },
            {
                "id": 1447969846,
                "nama": "Rhodes Robinson",
                "umur": 38,
                "status": "Positif",
                "kota": "Serang"
            },
            {
                "id": 1532274090,
                "nama": "Williams Nunez",
                "umur": 39,
                "status": "Negatif",
                "kota": "Bau-Bau"
            },
            {
                "id": 1402173521,
                "nama": "Laurie Tanner",
                "umur": 77,
                "status": "Positif",
                "kota": "Padang Sidempuan"
            },
            {
                "id": 1556149269,
                "nama": "Bailey Cohen",
                "umur": 62,
                "status": "Positif",
                "kota": "Pagaralam"
            },
            {
                "id": 1509775547,
                "nama": "Millie Gilmore",
                "umur": 30,
                "status": "Negatif",
                "kota": "Pagaralam"
            },
            {
                "id": 1433634256,
                "nama": "Tamika Ewing",
                "umur": 73,
                "status": "Negatif",
                "kota": "Tidore"
            },
            {
                "id": 1438917235,
                "nama": "Jarvis Santiago",
                "umur": 63,
                "status": "Belum Diketahui",
                "kota": "Pasuruan"
            },
            {
                "id": 1398041001,
                "nama": "Cooper Curtis",
                "umur": 65,
                "status": "Positif",
                "kota": "Payakumbuh"
            },
            {
                "id": 1417453937,
                "nama": "Vincent Pate",
                "umur": 67,
                "status": "Positif",
                "kota": "Bau-Bau"
            },
            {
                "id": 1558919452,
                "nama": "Jaime Vargas",
                "umur": 73,
                "status": "Negatif",
                "kota": "Kotamobagu"
            },
            {
                "id": 1561008841,
                "nama": "Ana Skinner",
                "umur": 41,
                "status": "Positif",
                "kota": "Subulussalam"
            },
            {
                "id": 1394341426,
                "nama": "Valenzuela Richmond",
                "umur": 16,
                "status": "Negatif",
                "kota": "Aceh"
            },
            {
                "id": 1570480050,
                "nama": "Barry Hudson",
                "umur": 59,
                "status": "Negatif",
                "kota": "Banjarmasi"
            },
            {
                "id": 1425816288,
                "nama": "Padilla Pierce",
                "umur": 14,
                "status": "Negatif",
                "kota": "Bima"
            },
            {
                "id": 1484865948,
                "nama": "Chasity Bowman",
                "umur": 16,
                "status": "Negatif",
                "kota": "Banjar"
            },
            {
                "id": 1412804398,
                "nama": "Myra Mclaughlin",
                "umur": 21,
                "status": "Negatif",
                "kota": "Parepare"
            },
            {
                "id": 1530624807,
                "nama": "Kendra Valenzuela",
                "umur": 77,
                "status": "Negatif",
                "kota": "Bandung"
            },
            {
                "id": 1538579415,
                "nama": "Patricia Lopez",
                "umur": 40,
                "status": "Belum Diketahui",
                "kota": "Mojokerto"
            },
            {
                "id": 1523150450,
                "nama": "Gill Greer",
                "umur": 29,
                "status": "Negatif",
                "kota": "Tangerang"
            },
            {
                "id": 1433845492,
                "nama": "Angel Gallegos",
                "umur": 36,
                "status": "Positif",
                "kota": "Tanjungpinang"
            },
            {
                "id": 1448588731,
                "nama": "Guthrie Wise",
                "umur": 25,
                "status": "Positif",
                "kota": "Kediri"
            },
            {
                "id": 1426953407,
                "nama": "Michelle Holland",
                "umur": 60,
                "status": "Belum Diketahui",
                "kota": "Solok"
            },
            {
                "id": 1405799150,
                "nama": "Lesley Kirkland",
                "umur": 57,
                "status": "Belum Diketahui",
                "kota": "Jakarta Timur"
            },
            {
                "id": 1551655142,
                "nama": "Tate Moore",
                "umur": 27,
                "status": "Belum Diketahui",
                "kota": "Bontang"
            },
            {
                "id": 1505107504,
                "nama": "Houston Mayer",
                "umur": 31,
                "status": "Positif",
                "kota": "Tasikmalay"
            },
            {
                "id": 1545464535,
                "nama": "Maldonado Landry",
                "umur": 66,
                "status": "Positif",
                "kota": "Sungai Penuh"
            },
            {
                "id": 1538151311,
                "nama": "Manning Quinn",
                "umur": 46,
                "status": "Belum Diketahui",
                "kota": "Subulussalam"
            },
            {
                "id": 1407496168,
                "nama": "Nancy Snider",
                "umur": 61,
                "status": "Belum Diketahui",
                "kota": "Jakarta Pusat"
            },
            {
                "id": 1511142643,
                "nama": "Cindy Ratliff",
                "umur": 12,
                "status": "Negatif",
                "kota": "Lhokseumawe"
            },
            {
                "id": 1439866994,
                "nama": "Mckinney Garrett",
                "umur": 79,
                "status": "Belum Diketahui",
                "kota": "Padang Sidempuan"
            },
            {
                "id": 1403112597,
                "nama": "Herring Hatfield",
                "umur": 78,
                "status": "Belum Diketahui",
                "kota": "Padang Sidempuan"
            },
            {
                "id": 1414740586,
                "nama": "Barr Simpson",
                "umur": 71,
                "status": "Positif",
                "kota": "Sorong"
            },
            {
                "id": 1419452960,
                "nama": "Brady Marshall",
                "umur": 44,
                "status": "Positif",
                "kota": "Sabang"
            },
            {
                "id": 1558497733,
                "nama": "Lopez Mckinney",
                "umur": 44,
                "status": "Belum Diketahui",
                "kota": "Medan"
            },
            {
                "id": 1438872505,
                "nama": "Summer Kinney",
                "umur": 34,
                "status": "Positif",
                "kota": "Salatiga"
            },
            {
                "id": 1477098973,
                "nama": "Letha Byrd",
                "umur": 60,
                "status": "Belum Diketahui",
                "kota": "Kediri"
            },
            {
                "id": 1438604589,
                "nama": "Dorothy Franklin",
                "umur": 54,
                "status": "Belum Diketahui",
                "kota": "Jakarta Selatan"
            },
            {
                "id": 1415401210,
                "nama": "Bradley Lucas",
                "umur": 75,
                "status": "Belum Diketahui",
                "kota": "Sibolga"
            },
            {
                "id": 1576940165,
                "nama": "Glenn Jensen",
                "umur": 53,
                "status": "Negatif",
                "kota": "Meulaboh"
            },
            {
                "id": 1501034656,
                "nama": "Petersen Rosa",
                "umur": 60,
                "status": "Negatif",
                "kota": "Salatiga"
            },
            {
                "id": 1572259568,
                "nama": "Bray Wall",
                "umur": 19,
                "status": "Negatif",
                "kota": "Probolinggo"
            },
            {
                "id": 1403821614,
                "nama": "Figueroa Galloway",
                "umur": 72,
                "status": "Positif",
                "kota": "Samarinda"
            },
            {
                "id": 1450145688,
                "nama": "Carol Caldwell",
                "umur": 13,
                "status": "Belum Diketahui",
                "kota": "Bitung"
            },
            {
                "id": 1579457265,
                "nama": "Jeanie Wood",
                "umur": 66,
                "status": "Negatif",
                "kota": "Palopo"
            },
            {
                "id": 1409802589,
                "nama": "Dianne Carney",
                "umur": 60,
                "status": "Positif",
                "kota": "Bau-Bau"
            },
            {
                "id": 1393170619,
                "nama": "Rosalinda Hawkins",
                "umur": 79,
                "status": "Positif",
                "kota": "Parepare"
            },
            {
                "id": 1507235127,
                "nama": "Daugherty Aguirre",
                "umur": 19,
                "status": "Negatif",
                "kota": "Magelang"
            },
            {
                "id": 1581894560,
                "nama": "Roslyn Clemons",
                "umur": 29,
                "status": "Negatif",
                "kota": "Pematangsiantar"
            },
            {
                "id": 1411778994,
                "nama": "Janice Floyd",
                "umur": 26,
                "status": "Positif",
                "kota": "Palangkaraya"
            },
            {
                "id": 1546730198,
                "nama": "Shannon Patterson",
                "umur": 64,
                "status": "Negatif",
                "kota": "Yogyakarta"
            },
            {
                "id": 1506611775,
                "nama": "Keri Mccray",
                "umur": 34,
                "status": "Negatif",
                "kota": "Purwokerto"
            },
            {
                "id": 1417283781,
                "nama": "Fulton Burt",
                "umur": 50,
                "status": "Positif",
                "kota": "Tasikmalay"
            },
            {
                "id": 1565894522,
                "nama": "Allen Mcclure",
                "umur": 16,
                "status": "Belum Diketahui",
                "kota": "Tangerang Selatan"
            },
            {
                "id": 1470145733,
                "nama": "Mayer Griffin",
                "umur": 21,
                "status": "Negatif",
                "kota": "Ambon"
            },
            {
                "id": 1510070764,
                "nama": "Wheeler Joyce",
                "umur": 70,
                "status": "Belum Diketahui",
                "kota": "Banjarbaru"
            },
            {
                "id": 1434055344,
                "nama": "Olive Burke",
                "umur": 15,
                "status": "Positif",
                "kota": "Manado"
            },
            {
                "id": 1563094206,
                "nama": "Lidia Wiggins",
                "umur": 12,
                "status": "Negatif",
                "kota": "Meulaboh"
            },
            {
                "id": 1542658095,
                "nama": "Robertson Horn",
                "umur": 54,
                "status": "Positif",
                "kota": "Tangerang Selatan"
            },
            {
                "id": 1487527372,
                "nama": "Jimmie Pratt",
                "umur": 17,
                "status": "Positif",
                "kota": "Lubuklinggau"
            },
            {
                "id": 1450636880,
                "nama": "Marquita Villarreal",
                "umur": 32,
                "status": "Belum Diketahui",
                "kota": "Sukabumi"
            },
            {
                "id": 1541177782,
                "nama": "Vega Kim",
                "umur": 29,
                "status": "Belum Diketahui",
                "kota": "Mojokerto"
            },
            {
                "id": 1479256967,
                "nama": "Wilder Graham",
                "umur": 37,
                "status": "Positif",
                "kota": "Tual"
            },
            {
                "id": 1534326841,
                "nama": "Patti Weber",
                "umur": 77,
                "status": "Positif",
                "kota": "Singkawang"
            },
            {
                "id": 1431089661,
                "nama": "Morgan Bender",
                "umur": 18,
                "status": "Belum Diketahui",
                "kota": "Balikpapan"
            },
            {
                "id": 1466074102,
                "nama": "Julie Saunders",
                "umur": 30,
                "status": "Positif",
                "kota": "Tasikmalay"
            },
            {
                "id": 1522489619,
                "nama": "Melisa Patrick",
                "umur": 38,
                "status": "Belum Diketahui",
                "kota": "Belitung"
            },
            {
                "id": 1437095740,
                "nama": "Ella Slater",
                "umur": 65,
                "status": "Positif",
                "kota": "Metro"
            },
            {
                "id": 1390459697,
                "nama": "Hays Jordan",
                "umur": 43,
                "status": "Negatif",
                "kota": "Cimahi"
            },
            {
                "id": 1396145442,
                "nama": "Reyes Rose",
                "umur": 63,
                "status": "Belum Diketahui",
                "kota": "Tarakan"
            },
            {
                "id": 1525850202,
                "nama": "Dolores Howe",
                "umur": 45,
                "status": "Negatif",
                "kota": "Kupang"
            },
            {
                "id": 1441083395,
                "nama": "Anastasia Pena",
                "umur": 30,
                "status": "Negatif",
                "kota": "Pekanbaru"
            },
            {
                "id": 1505028534,
                "nama": "Goff Cortez",
                "umur": 74,
                "status": "Negatif",
                "kota": "Padang"
            },
            {
                "id": 1488946730,
                "nama": "Kaufman Kline",
                "umur": 80,
                "status": "Positif",
                "kota": "Palu"
            },
            {
                "id": 1529413770,
                "nama": "Mable Callahan",
                "umur": 57,
                "status": "Negatif",
                "kota": "Binjai"
            },
            {
                "id": 1389719819,
                "nama": "Dalton Clay",
                "umur": 63,
                "status": "Belum Diketahui",
                "kota": "Mataram"
            }
        ]

### Add Patient [POST]
+ Request (application/json)

        {
            "id": 0,
            "nama": "Joko",
            "umur": 90,
            "status": "Positif",
            "kota": "Jakarta"
        }

+ Response 201 (application/json)

    + Headers

            Location: /patient-list

    + Body

            {
                "id": 0,
                "nama": "Joko",
                "umur": 90,
                "status": "Positif",
                "kota": "Jakarta"
            }

## City [/city-list]
### Get City List [GET]
+ Response 200 (application/json)

        [
            "Aceh",
            "Langsa",
            "Lhokseumawe",
            "Meulaboh",
            "Sabang",
            "Subulussalam",
            "Denpasar",
            "Belitung",
            "Cilegon",
            "Serang",
            "Tangerang Selatan",
            "Tangerang",
            "Bengkulu",
            "Gorontalo",
            "Jakarta Barat",
            "Jakarta Pusat",
            "Jakarta Selatan",
            "Jakarta Timur",
            "Jakarta Utara",
            "Sungai Penuh",
            "Jambi",
            "Bandung",
            "Bekasi",
            "Bogo",
            "Cimahi",
            "Cirebon",
            "Depok",
            "Sukabumi",
            "Tasikmalay",
            "Banjar",
            "Magelang",
            "Pekalongan",
            "Purwokerto",
            "Salatiga",
            "Semarang",
            "Surakarta",
            "Tegal",
            "Batu",
            "Blitar",
            "Kediri",
            "Madiun",
            "Malang",
            "Mojokerto",
            "Pasuruan",
            "Probolinggo",
            "Surabaya",
            "Pontianak",
            "Singkawang",
            "Banjarbaru",
            "Banjarmasi",
            "Palangkaraya",
            "Balikpapan",
            "Bontang",
            "Samarinda",
            "Tarakan",
            "Batam",
            "Tanjungpinang",
            "Lampung",
            "Metro",
            "Ternate",
            "Tidore",
            "Ambon",
            "Tual",
            "Bima",
            "Mataram",
            "Kupang",
            "Sorong",
            "Jayapura",
            "Dumai",
            "Pekanbaru",
            "Makassar",
            "Palopo",
            "Parepare",
            "Palu",
            "Bau-Bau",
            "Kendari",
            "Bitung",
            "Kotamobagu",
            "Manado",
            "Tomohon",
            "Bukittinggi",
            "Padang",
            "Padangpanjang",
            "Pariaman",
            "Payakumbuh",
            "Sawahlunto",
            "Solok",
            "Lubuklinggau",
            "Pagaralam",
            "Palembang",
            "Prabumulih",
            "Binjai",
            "Medan",
            "Padang Sidempuan",
            "Pematangsiantar",
            "Sibolga",
            "Tanjungbalai",
            "Tebingtinggi",
            "Yogyakarta"
        ]

## Patient Status [/patient-status-list]
### Get Patient Status [GET]
+ Response 200 (application/json)

        [
            "Positif",
            "Negatif",
            "Belum Diketahui",
            "Meniggal",
            "Sembuh"
        ]